(:name           "python")
(:repo           "taffish-org/python")
(:author         "KaiyuanHan")
(:version        "3.12.9")
(:intro          "Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation.")
(:dependencies)
(:functions      "[default python 3.12.9]")
